### ISSUE TITLE
Working Contract - Holiday on half day public holiday not possible

### ISSUE THREAD

**Issue by hw-rjuzak** [kimai/Paid-plugins#116]
Hello and happy new year!

Many thanks for the plugin. It allowed us to migrate from an old tool and use Kimai exclusively.

We just hit a bug related to public holidays. We defined the Christmas Eve and New Year Eve as a half day holiday.

![image](https://github.com/kevinpapst/kimai-plugins/assets/86657989/60c8f570-7be0-483c-a68a-3a1c26cd6bb4)

It's not possible to take a Half day holiday on those days :/

![image](https://github.com/kevinpapst/kimai-plugins/assets/86657989/1cb17001-a3b5-419f-9d04-cf4dc5e28c1b)

You can select a range, and it will create holidays for the selected range, and skip the holidays in between (thanks the previous release)

![image](https://github.com/kevinpapst/kimai-plugins/assets/86657989/2a3a4a9f-b2cb-44a8-a0de-b7a0f1dda1c5)

![image](https://github.com/kevinpapst/kimai-plugins/assets/86657989/4e86d914-e895-43e6-abe7-f34382624a75)

But you are not change it to half day. So the calculated vacation days is wrong (should be 4 taken)

![image](https://github.com/kevinpapst/kimai-plugins/assets/86657989/881ee9b9-7b19-435a-b0b6-89b49fd8801b)

**Comment by kevinpapst** [comment]
Oh, that's a tricky one.

Thanks for the bug report, I'll look into it.

**Comment by patrickrobrecht** [comment]
This bug seems to be fixed in Kimai 2.20.0 + Working Contract 1.12.

**Comment by kevinpapst** [comment]
Yap, that should be fixed now. Thanks for confirming!
