### ISSUE TITLE
Working Contract: Keep filter

### ISSUE THREAD

**Issue by HeinzWuert** [kimai/Paid-plugins#120]
Use as admin:
I select any user under working contract.
Unfortunately, the selection always jumps back to the first user in the selection list as soon as you switch between the working contract submenus.

Solution:
Keep the user selection/filters as long as you work under Working Contract

Idea: A button in Working Times keeping the filter and jumping to the other submenu whereas a click on the submenu resets the filter.

**Comment by kevinpapst** [comment]
was added to a recent version
