### ISSUE TITLE
Plugin Employee account: manual adjustments for holidays - half days possible?

### ISSUE THREAD

**Issue by david-proba** [kimai/Paid-plugins#121]
added in version 1.4: manual adjustments for holidays, e.g. top up available days with remaining days from last year
Is it possible to adjust e.g. 2.5 days from last year?
At the moment with version 1.5 of the employee account plugin I can only adjust full days.
![Bildschirmfoto vom 2024-01-15 15-44-58](https://github.com/kevinpapst/kimai-plugins/assets/156685774/6db2003e-53bb-47c5-9ee9-147a70278f5b)

**Comment by kevinpapst** [comment]
was added to a recent version

**Comment by DarianAnjuhal** [comment]
Thx, I could find it, and its working!
