### ISSUE TITLE
API query to connect tasks and time sheets

### ISSUE THREAD

**Issue by niels-przybilla** [kimai/Paid-plugins#154]
### Discussed in https://github.com/kevinpapst/kimai-plugins/discussions/149

<div type='discussions-op-text'>

<sup>Originally posted by **niels-przybilla** April 17, 2024</sup>
Hi Kimai Community,

referring to this discussion: https://github.com/kimai/kimai/discussions/4188
It would be helpful to connect tasks and timesheets with API as we want to import the tracked time with tasks into another invoiceing system

Many thanks and best wishes

Niels</div>

**Comment by kevinpapst** [comment]
You can get the latest version including a route to "fetch the timesheets for a task" at 
https://license.kimai.org/

**Comment by niels-przybilla** [comment]
Good day @kevinpapst ,

i updated Kimai to 2.17.0 and TaskBundle to 2.8.0. But i do not see this endpoint: 
![image](https://github.com/kimai/Paid-plugins/assets/99684821/72ffd4cb-b06c-4539-b6c6-6670c9b6de2a)

This is my Swagger:

![Monosnap Kimai - API Docs 2024-06-03 07-25-35](https://github.com/kimai/Paid-plugins/assets/99684821/2c62085b-fe66-474c-addd-2f442a15bdf3)

WHat did i do wrong?

THX and best wishes

Niels

**Comment by kevinpapst** [comment]
You need version 2.9

**Comment by niels-przybilla** [comment]
HaHa I see 😊 I was too fast this morning. Thank you!

Von: Kevin Papst ***@***.***>
Datum: Montag, 3. Juni 2024 um 20:42
An: kimai/Paid-plugins ***@***.***>
Cc: Niels Przybilla ***@***.***>, Author ***@***.***>
Betreff: Re: [kimai/Paid-plugins] API query to connect tasks and time sheets (Issue #154)

You need version 2.9
