### ISSUE TITLE
Disable visibility of Activity throws error

### ISSUE THREAD

**Issue by markus7777777** [kimai/Paid-plugins#164]
### Discussed in https://github.com/kimai/Paid-plugins/discussions/163

<div type='discussions-op-text'>

<sup>Originally posted by **markus7777777** June  2, 2024</sup>
Hi everyone.

I'm having trouble disabling the visibility of an activity. The same issue occurs when I try to edit an activity and add a tag to it.

**Kimai Version: 2.17.0
Custom fields version: 2.0.7**

**Log:**
`[2024-06-02 08:25:11] [request] CRITICAL: Uncaught PHP Exception Error: "Call to a member function toArray() on array" at TagsExtension.php line 64 {"exception":"[object] (Error(code: 0): Call to a member function toArray() on array at /var/www/kimai/var/plugins/MetaFieldsBundle/Form/Extension/TagsExtension.php:64)"} []
[2024-06-02 08:25:11] [request] INFO: Matched route "admin_activity_edit". {"route":"admin_activity_edit","route_parameters":{"_route":"admin_activity_edit","_controller":"App\\Controller\\ActivityController::editAction","_locale":"de_AT","id":"38"},"request_uri":"http://kimai.local/activity/38/edit","method":"POST"} []`

**Does anyone have any ideas on how to solve this?**

![image](https://github.com/kimai/Paid-plugins/assets/46875900/76f9b942-8458-425f-bb61-60ae504dc035)

</div>

**Comment by pbksol** [comment]
Just update des Custom Fields Plugin to the latest version and the error will go away.

**Comment by markus7777777** [comment]
I bought the new version of the plugin but that didn't solve the issue.

The Auto Tag Column inside activities responds : "A string is necessary"

If i want to disable the custom field - the error from my initial issue pops up.

```
[2024-06-02 15:13:45] [request] CRITICAL: Uncaught PHP Exception Error: "Call to a member function getValues() on array" at MetaFieldRuleForm.php line 161 {"exception":"[object] (Error(code: 0): Call to a member function getValues() on array at /var/www/kimai/var/plugins/MetaFieldsBundle/Form/MetaFieldRuleForm.php:161)"} []
[2024-06-02 15:13:44] [request] INFO: Matched route "custom_meta_fields_edit". {"route":"custom_meta_fields_edit","route_parameters":{"_route":"custom_meta_fields_edit","_controller":"KimaiPlugin\\MetaFieldsBundle\\Controller\\MetaFieldsController::editAction","_locale":"de","id":"45"},"request_uri":"http://kimai.local/de/admin/custom-meta-fields/45/edit","method":"POST"} []
```



![image](https://github.com/kimai/Paid-plugins/assets/46875900/34b67e5c-3bb4-4429-908b-e44760f87860)

**Comment by kevinpapst** [comment]
You don't need to buy a new version for an update. 

> If i want to disable the custom field - the error from my initial issue pops up.

What does that mean? How do you try to disable the field? Do you mean if you remove all tags from the field?

**Comment by kevinpapst** [comment]
You need at least the plugin version 2.6. better 2.7.0.

Can you show me the output:

```bash
bin/console kimai:version
bin/console kimai:plugins
```

**Comment by markus7777777** [comment]
I had to purchase a new version because it was no longer available in my Lemonsqueezy account. I dont know why?

**_What does that mean? How do you try to disable the field? Do you mean if you remove all tags from the field?_**

My aim is to edit activities -> rename them -> add further tags -> disable visibility of some activites...
All of these scenarios dont work.

bin/console kimai:version -> Kimai 2.17.0 by Kevin Papst.


![image](https://github.com/kimai/Paid-plugins/assets/46875900/c56528c2-029f-4115-b8c3-8b0e4ff93131)

**Comment by markus7777777** [comment]
> You need at least the plugin version 2.6. better 2.7.0.
> 
> Can you show me the output:
> 
> ```shell
> bin/console kimai:version
> bin/console kimai:plugins
> ```

The latest Plugin Version available is 2.5.0 (LemonSqueezy)

**Comment by kevinpapst** [comment]
Please login at https://license.kimai.org/ and fetch the latest version

**Comment by markus7777777** [comment]
I updated the Bundle but the error is still here.

![image](https://github.com/kimai/Paid-plugins/assets/46875900/55924aa1-bbd2-4dd0-84d3-8e82982e9190)
![image](https://github.com/kimai/Paid-plugins/assets/46875900/8ebf182c-66e7-487e-96a0-2ac3268e5ee2)

**Comment by kevinpapst** [comment]
I am not able to reproduce it. 
Sorry, but can you try to reproduce it in the demo: https://www.kimai.org/en/demo.html
If it works there, what is it that you are doing exactly? Like step-by-step.

**Comment by markus7777777** [comment]
Thank you very much for your help. I tried to reproduce the problem on the demo version. In the demo it works fine and without any problems.

Please have a look into the attached pdf where I tried to reproduce the error.

[Problem_Tags_Edit_Activity.pdf](https://github.com/user-attachments/files/15604185/Problem_Tags_Edit_Activity.pdf)

**Comment by kevinpapst** [comment]
Ok, I think found the problem. 
If you have a lot of tags (more than 500) another dropdown type is used.
And one of them fails.

**Comment by markus7777777** [comment]
<img width="500" alt="image" src="https://github.com/kimai/Paid-plugins/assets/46875900/1081a170-198b-412a-ae4d-e527ab250bc6">

For this tag there are 7087 Timesheet entries. In sum, we have 3 different Tags.

**Comment by kevinpapst** [comment]
Can you please update to plugin version 2.8.0 and retry?

**Comment by markus7777777** [comment]
> Can you please update to plugin version 2.8.0 and retry?

Thanks a lot! That solved the issue!
