### ISSUE TITLE
Employment contract - employee start/end date

### ISSUE THREAD

**Issue by StefanGebhardt** [kimai/Paid-plugins#166]
### Describe the problem

When a new employee starts (or ends) in the year, the week view does not help.
Example: the employee begins in the company on the first of May. As I can't enter this start date, Kimai begins the working times in the week view in January. So the employee has minus-hours for the first four month.

### Describe the solution you'd like

Not only the possibility to define work hours for a user, but also a start/end time. And Kimai only calculates the hours after the start and before the end time.

### Screenshots

<img width="995" alt="image" src="https://github.com/kimai/kimai/assets/2803552/2fcaf208-2fde-4df0-9355-c230b3126f3c">

**Comment by kevinpapst** [comment]
Possible with https://www.kimai.org/store/controlling.html

<img width="911" alt="Bildschirmfoto 2024-06-04 um 16 00 55" src="https://github.com/kimai/Paid-plugins/assets/533162/ad248c4d-36bd-4fa7-a2db-9766da8ed3e2">

<img width="1271" alt="Bildschirmfoto 2024-06-04 um 16 01 49" src="https://github.com/kimai/Paid-plugins/assets/533162/73a9538b-e6b7-4e02-8496-d1066061e59e">

**Comment by StefanGebhardt** [comment]
Thanks @kevinpapst for the fast reply. Unfortunately a bit expensive for me as a small company. But fully understandable :-)
