### ISSUE TITLE
AuditTrailBundle: route "audit_logs" does not exist

### ISSUE THREAD

**Issue by niclashoyer** [kimai/Paid-plugins#168]
After installing the AuditTrailBundle we get a 500 error on every page with the following exception:

```
[2024-06-07 09:21:51] [request] CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown
during the rendering of a template ("Unable to generate a URL for the named route "audit_logs" as such route does not ex
ist.")." at /var/www/kimai/vendor/kevinpapst/tabler-bundle/templates/includes/menu.html.twig line 65 {"exception":"[obje
ct] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Unable to ge
nerate a URL for the named route \"audit_logs\" as such route does not exist.\"). at /var/www/kimai/vendor/kevinpapst/ta
bler-bundle/templates/includes/menu.html.twig:65)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception
\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"audit_logs\" as such route does not ex
ist. at /var/www/kimai/vendor/symfony/routing/Generator/CompiledUrlGenerator.php:50)"}
```

We already tried to debug this, but everything seems to be correct. The corresponding route is defined in `var/plugins/AuditTrailBundle/Controller/AuditListing.php` and the plugin is loaded correctly as it is listed at `bin/console kimai:plugin`.

**Comment by kevinpapst** [comment]
Please share your Kimai version and the Plugin version.

Do you see Administration > Audit logs?

<img width="242" alt="Bildschirmfoto 2024-06-07 um 11 40 13" src="https://github.com/kimai/Paid-plugins/assets/533162/d91e6fbb-98fd-4884-9adb-91e10cd5d4fb">

**Comment by niclashoyer** [comment]
Can't reach the admin, just the same 500 error on every page. We are on Kimai 2.5.0 and the bundle is at 2.6.0.

**Comment by pbksol** [comment]
Kimai is stone old. The current version is 2.17.0. You should update Kimai and try again.

**Comment by kevinpapst** [comment]
I guess the announced compatibility is wrong. Updating Kimai is the safest option!
