### ISSUE TITLE
Bug: If only half holiday is left, one cannot even enter a half holiday.

### ISSUE THREAD

**Issue by patrickrobrecht** [kimai/Paid-plugins#183]
If all holidays for a user except a half one have been taken already, this half one cannot be ordered because the button for entering holidys is disabled.

Temporary workaround: Delete a holiday, book the half day, reenter the deleted holiday.

**Comment by kevinpapst** [comment]
Thanks for finding, will be fixed with the next release 1.13.0

**Comment by kevinpapst** [comment]
I think I fixed the last edge case with version 1.16 of the plugin. 
Download it at: https://license.kimai.org/
