### ISSUE TITLE
Custom fields: timesheet custom fields not contained in export

### ISSUE THREAD

**Issue by de-sec** [kimai/Paid-plugins#190]
## Describe the problem
Hi everyone, 

we recently created a new custom field to track the travel distance in addition to the rare travel time in a single timesheet record - this custom field is restricted to the travel-time task we're using. 

Our issue is the following: the content of the custom field is displayed / exported only if we filter for this specific task prior to the export, which isn't optimal for our needs.

Update: Versions:
Kimai: 2.21.0
Custom Fields: 2.9.0

### what we have tried
setting the custom field to "visible" > doesn't affect the export
Exports with a filter set to the task, which the custom field is limited to > works - but its not a solution as we need an export of the whole last month, containing all recorded tasks
Removing the limitation of the custom field > works but not suitable for our needs.

## Describe the solution you'd like
We'd like to have the option to choose either if a limited / restricted custom fields is contained in an export or not. 

## Describe alternatives you've considered
Non-restricting the mentioned custom field isn't a real solution, as we don't want to handle the travel-distance on the "working" tasks.

Best regards

**Comment by kevinpapst** [comment]
What you ask for will not be added, sorry. 

The workflow isn't good and I was planning on actually removing the visibility restriction altogether, as they are impossible to use properly. As you experience already.
