### ISSUE TITLE
Calculation of “other” absences after Upgrade to plugin version 1.13 wrong

### ISSUE THREAD

**Issue by david-proba** [kimai/Paid-plugins#193]
We are using Kimai Version 2.21. After upgrading Working Contract plugin from Version 1.12 to 1.13 “other” absences with a duration < daily working hours (e.g. < 8:00) are calculated as 8:00 hours, so the total amount of a month is wrong. With plugin version 1.12 everything has been correct.

**Comment by kevinpapst** [comment]
Can you clarify (with screenshots)?

I changed the input form, to allow defining a duration for "other" absences.

**Comment by david-proba** [comment]
![Bildschirmfoto vom 2024-09-18 12-41-27](https://github.com/user-attachments/assets/7d16d20d-65cd-4ae2-9985-b1433fbddd08)
![Bildschirmfoto vom 2024-09-16 09-21-04](https://github.com/user-attachments/assets/355fbf95-8678-42c6-b33a-c426dd72880e)
![Bildschirmfoto vom 2024-09-18 12-40-13](https://github.com/user-attachments/assets/dfdaf706-73ef-44f7-a227-9c1ffdeb3742)

the screenshots show the days 21.08-23.08. 21.08.: 2:30 working hours and 3:30 other absence = 6:00 hours ( -2:00 ) ; 23.08.: 4:30 working hours and 4:30 others absence = 9:00 hours ( +1:00 )   ,  but the overview shows +2:30 and +4:30 and August summary +8:00 hours

**Comment by kevinpapst** [comment]
Thanks, will setup a demo and verify.

**Comment by kevinpapst** [comment]
I found the issue and will release an update during the weekend. Thanks 👍

**Comment by kevinpapst** [comment]
I released a new version, you can test if that fixes the issue for you. 

I added new features as well, which unfortunately need the latest Kimai version 2.22.0 - so you need to update both.

**Comment by david-proba** [comment]
I can confirm that the issue has been solved with the new version. Thank you for providing a new version so quickly.

**Comment by kevinpapst** [comment]
Wow, not many people can upgrade their Kimai that quickly. 

Thanks for your feedback 😄
