### ISSUE TITLE
Employee account: Working hours, holiday, sickness, public holidays - taking half-day vacation not possible.

### ISSUE THREAD

**Issue by intelliIT** [kimai/Paid-plugins#198]
we have one employee who wants to take half a vacation day off for this year new years eve. the employee already took 12.5 of 13 available vacation days this year. now the system responds with an error message.

new-years eve is defined as half-day holiday.
when i try to take new years eve off it implicitly writes it down as only half a vacation day.

<details>
<summary>screenshots</summary>
<img width="620" alt="image" src="https://github.com/user-attachments/assets/ff48e971-5a7b-474c-bbc6-abff2ce6c30f">
<img width="788" alt="image" src="https://github.com/user-attachments/assets/e97e555e-72bd-4dd7-802b-3d229fd50235">
</details>

running kimai2:apache-2.18.0-prod in docker
WorkingContract Version 1.3.0 

help would be appreciated; thank you.

**Comment by kevinpapst** [comment]
Check the Changelog tab at https://www.kimai.org/store/controlling.html

We are at version 1.13 and half-day vacations already received a few updates/bugfixes.

Grab your update at https://license.kimai.org/ and test if that fixes it.

**Comment by pkoevesdi** [comment]
Had a similar problem and can confirm: works as expected now in Work contract 1.14.0
