### ISSUE TITLE
strange buttons in absence screen

### ISSUE THREAD

**Issue by pkoevesdi** [kimai/Paid-plugins#201]
After Upgrading to Working hours 1.15, the buttons on the absence screen look "different":
![grafik](https://github.com/user-attachments/assets/c5537d59-466f-4708-86f4-ccc8f7810fa0)

**Comment by pkoevesdi** [comment]
Ah, ok, sorry for rushing the update.

**Comment by pkoevesdi** [comment]
Bug still exists with Kimai 2.26.0 and Working Contract Plugin 1.15.0.

**Comment by kevinpapst** [comment]
Just released Plugin v1.16
