### ISSUE TITLE
Internal server error after update

### ISSUE THREAD

**Issue by pkoevesdi** [kimai/Paid-plugins#202]
After Upgrading Kimai from 2.23.0 to 2.25.0, we get an internal server error when opening the absence screen `/de/absence/` for a user who has entries there. It still works for users, who have no entries yet (for instance new users), except #201.
It was the case with Working Contract 1.14 already, and didn't change after upgrding to 1.15.

**Comment by pkoevesdi** [comment]
I'm not sure, if it depends on having entries there or not. I tested it: deleted my own entries from the database `kimai2_holidays_manual` table, still I have this error on my account. Still on a new account, this error is not there.

**Comment by kevinpapst** [comment]
Same issue. Kimai 2.25 is not compatible. 
New and compatible plugin version will be available this week.

If you can: downgrade to 2.24.

Otherwise disable the Absence screen for two days. 
Do not tinker with the database, this does not solve anything.

Sorry!

**Comment by kevinpapst** [comment]
Should be fixed with 2.26 => https://github.com/kimai/kimai/releases/tag/2.26.0
