### ISSUE TITLE
absences not showing

### ISSUE THREAD

**Issue by pkoevesdi** [kimai/Paid-plugins#208]
Hope I didn't miss something or so something wrong, but on some of our employees not all or even none of the booked absences show up in `/de/absence/`:
![grafik](https://github.com/user-attachments/assets/63ae844d-fa35-4118-bdaa-b09486adf1e5)

But ths sum "Sie haben bisher 6 von Ihren verfügbaren 9 Urlaubstagen genommen. " is correct and also they show up in `/de/contract`:
![grafik](https://github.com/user-attachments/assets/990c662b-3cfa-4c46-9bad-4f26ec037a73)

**Comment by kevinpapst** [comment]
Please install the latest version: 1.16.2
