### ISSUE TITLE
Absence: can't take half day holiday on a half day public holiday

### ISSUE THREAD

**Issue by ckorge** [kimai/Paid-plugins#210]
In our company there are company-agreed half public holidays. For example, the 24th of December. If you want to have the whole day off, you have to take half a day's holiday. I can't apply for this in Kimai, with the reference that the selected day is not a working day.

![Bildschirmfoto vom 2024-12-13 11-34-45](https://github.com/user-attachments/assets/86b01262-d0b5-48bf-a60b-736c5129f327)
![Bildschirmfoto vom 2024-12-13 11-46-23](https://github.com/user-attachments/assets/edbb2a03-39d2-4c4d-823d-403726d7ad66)

**Comment by kevinpapst** [comment]
Which plugin version are you using?

**Comment by ckorge** [comment]
1.5.0

**Comment by kevinpapst** [comment]
Please update both Kimai and the plugin to the latest version.
I just tried it and in my environment:
- if the public holiday is a full-day, the vacation booking is rejected
- if the public holiday is half-day, booking a half-day vacation is possible
- if the public holiday is half-day, booking a full-day vacation automatically switches it to "half day vacation"
