### ISSUE TITLE
Working times: view full sum

### ISSUE THREAD

**Issue by n0emis** [kimai/Paid-plugins#95]
An option to show the full sum of over-/undertime since a user has started working at a company would be really nice, because at our company we are allowing people to carry this into other years. Even better would be, if the sum could be displayed while on another screen (e.g. as a pill in the sidebar at the contract section)

**Comment by kevinpapst** [comment]
You have to carry over times from one year to the next year manually per year with "manual bookings".

The value can be seen by clicking either the "Absence" or "Working time" screen.
Adding the value as widgets to the dashboard is good.

But why would you want to see it all the time? Doesn't make sense to me: the value is either too high (which is not encouraging or it is too low, which is also not encouraging).

**Comment by kevinpapst** [comment]
The "overall total sum" is always the total of the current year.
